# -*- coding: utf-8 -*-
"""salarypred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDVsUh8kglD4LneUVvDZyLJMYwyqjYKR
"""

import pandas as pd

df = pd.read_csv('/content/Salary_Dataset_DataScienceLovers (1).csv')
df

df.isnull().sum()

for column in df.columns:
  if df[column].dtype == 'object':
    if df[column].isnull().any():
      df[column] = df[column].fillna(df[column].mode()[0])
  else:
    if df[column].isnull().any():
      df[column] = df[column].fillna(df[column].mode()[0])

print(df.isnull().sum())

from sklearn.preprocessing import LabelEncoder

label_encoders = {}
categorical_cols = ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']

for column in categorical_cols:
  if column in df.columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le
    print(f"Encoded column: {column}")

display(df.head())

import pickle
from google.colab import files

# Define the filename for the label encoders
label_encoders_filename = 'label_encoders.pkl'

# Save the label_encoders dictionary to the .pkl file
with open(label_encoders_filename, 'wb') as file:
    pickle.dump(label_encoders, file)

print(f"Label encoders saved as {label_encoders_filename}")

# Provide a link to download the file
files.download(label_encoders_filename)

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### 1. Linear Regression Model"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Initialize the Linear Regression model
linear_model = LinearRegression()

# Train the model
linear_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_lr = linear_model.predict(X_test)

# Evaluate the model
mae_lr = mean_absolute_error(y_test, y_pred_lr)
mse_lr = mean_squared_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mse_lr)
r2_lr = r2_score(y_test, y_pred_lr)

print("Linear Regression Model Evaluation:")
print(f"Mean Absolute Error (MAE): {mae_lr:.2f}")
print(f"Mean Squared Error (MSE): {mse_lr:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_lr:.2f}")
print(f"R-squared (R2): {r2_lr:.2f}")

"""### 2. K-Nearest Neighbors (KNN) Regressor"""

from sklearn.neighbors import KNeighborsRegressor

# Initialize the KNN Regressor model (you can tune n_neighbors)
knn_model = KNeighborsRegressor(n_neighbors=5)

# Train the model
knn_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_knn = knn_model.predict(X_test)

# Evaluate the model
mae_knn = mean_absolute_error(y_test, y_pred_knn)
mse_knn = mean_squared_error(y_test, y_pred_knn)
rmse_knn = np.sqrt(mse_knn)
r2_knn = r2_score(y_test, y_pred_knn)

print("K-Nearest Neighbors Regressor Model Evaluation:")
print(f"Mean Absolute Error (MAE): {mae_knn:.2f}")
print(f"Mean Squared Error (MSE): {mse_knn:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_knn:.2f}")
print(f"R-squared (R2): {r2_knn:.2f}")

"""### 3. Decision Tree Regressor"""

from sklearn.tree import DecisionTreeRegressor

# Initialize the Decision Tree Regressor model
dt_model = DecisionTreeRegressor(random_state=42)

# Train the model
dt_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_dt = dt_model.predict(X_test)

# Evaluate the model
mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
rmse_dt = np.sqrt(mse_dt)
r2_dt = r2_score(y_test, y_pred_dt)

print("Decision Tree Regressor Model Evaluation:")
print(f"Mean Absolute Error (MAE): {mae_dt:.2f}")
print(f"Mean Squared Error (MSE): {mse_dt:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_dt:.2f}")
print(f"R-squared (R2): {r2_dt:.2f}")

"""### 4. Random Forest Regressor"""

from sklearn.ensemble import RandomForestRegressor

# Initialize the Random Forest Regressor model
rf_model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Random Forest Regressor Model Evaluation:")
print(f"Mean Absolute Error (MAE): {mae_rf:.2f}")
print(f"Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_rf:.2f}")
print(f"R-squared (R2): {r2_rf:.2f}")

"""### 5. Gaussian Naive Bayes (for regression-like problem)"""

from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler

# Naive Bayes models are typically for classification.
# For regression, a common approach is to discretize the target variable
# or use a variant that can handle continuous output, though it's not a direct regression algorithm.
# Here, we'll use Gaussian Naive Bayes, which can be adapted by fitting to the continuous values.
# It assumes features are independent and follow a Gaussian distribution.

# Scale the features for better performance with some models
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize Gaussian Naive Bayes model
nb_model = GaussianNB()

# Train the model (Note: Naive Bayes is a classifier, fitting to continuous 'y' directly might not be optimal for regression tasks)
# For a true regression, one might discretize 'y' or use a different algorithm.
# Here, we're fitting it in a way that it will try to predict the class (salary value) based on the learned distributions.
nb_model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred_nb = nb_model.predict(X_test_scaled)

# Evaluate the model
mae_nb = mean_absolute_error(y_test, y_pred_nb)
mse_nb = mean_squared_error(y_test, y_pred_nb)
rmse_nb = np.sqrt(mse_nb)
r2_nb = r2_score(y_test, y_pred_nb)

print("Gaussian Naive Bayes Model Evaluation:")
print(f"Mean Absolute Error (MAE): {mae_nb:.2f}")
print(f"Mean Squared Error (MSE): {mse_nb:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse_nb:.2f}")
print(f"R-squared (R2): {r2_nb:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Create a DataFrame for model evaluation results
model_names = ['Linear Regression', 'KNN Regressor', 'Decision Tree Regressor', 'Random Forest Regressor', 'Gaussian Naive Bayes']
metrics_data = {
    'Model': model_names,
    'MAE': [mae_lr, mae_knn, mae_dt, mae_rf, mae_nb],
    'MSE': [mse_lr, mse_knn, mse_dt, mse_rf, mse_nb],
    'RMSE': [rmse_lr, rmse_knn, rmse_dt, rmse_rf, rmse_nb],
    'R-squared': [r2_lr, r2_knn, r2_dt, r2_rf, r2_nb]
}
results_df = pd.DataFrame(metrics_data)

display(results_df)

"""### Visual Comparison of Model Performance"""

fig, axes = plt.subplots(2, 2, figsize=(18, 12))
fig.suptitle('Comparison of Regression Model Performance Metrics', fontsize=16)

# MAE
sns.barplot(ax=axes[0, 0], x='Model', y='MAE', data=results_df, palette='viridis')
axes[0, 0].set_title('Mean Absolute Error (MAE)')
axes[0, 0].set_xticklabels(axes[0, 0].get_xticklabels(), rotation=45, ha='right')

# MSE
sns.barplot(ax=axes[0, 1], x='Model', y='MSE', data=results_df, palette='magma')
axes[0, 1].set_title('Mean Squared Error (MSE)')
axes[0, 1].set_xticklabels(axes[0, 1].get_xticklabels(), rotation=45, ha='right')

# RMSE
sns.barplot(ax=axes[1, 0], x='Model', y='RMSE', data=results_df, palette='cividis')
axes[1, 0].set_title('Root Mean Squared Error (RMSE)')
axes[1, 0].set_xticklabels(axes[1, 0].get_xticklabels(), rotation=45, ha='right')

# R-squared
sns.barplot(ax=axes[1, 1], x='Model', y='R-squared', data=results_df, palette='plasma')
axes[1, 1].set_title('R-squared (R2) Score')
axes[1, 1].set_xticklabels(axes[1, 1].get_xticklabels(), rotation=45, ha='right')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

import pickle
from google.colab import files

# Define the filename for the best model (Linear Regression in this case)
model_filename = 'linear_regression_model.pkl'

# Save the linear_model to the .pkl file
with open(model_filename, 'wb') as file:
    pickle.dump(linear_model, file)

print(f"Model saved as {model_filename}")

# Provide a link to download the file
files.download(model_filename)

"""### Create `requirements.txt`

This section will generate a `requirements.txt` file containing the major Python libraries used in this notebook, along with their current versions.
"""

import pkg_resources

# List of packages to include in requirements.txt
packages = [
    'pandas',
    'scikit-learn', # sklearn
    'numpy',
    'matplotlib',
    'seaborn'
]

# Get the installed version of each package
installed_packages = []
for pkg_name in packages:
    try:
        version = pkg_resources.get_distribution(pkg_name).version
        installed_packages.append(f'{pkg_name}=={version}')
    except pkg_resources.DistributionNotFound:
        installed_packages.append(f'{pkg_name} # Not found, please specify version manually')

# Write to requirements.txt
with open('requirements.txt', 'w') as f:
    for pkg in installed_packages:
        f.write(pkg + '\n')

print("requirements.txt created successfully:")
for pkg in installed_packages:
    print(pkg)

from google.colab import files
files.download('requirements.txt')

"""### Streamlit Application for Salary Prediction

Now, let's create the Streamlit application file (`deploy_app.py`). This file will contain the logic to load the model and label encoders, take user input, and display the predicted salary.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile deploy_app.py
# 
# import streamlit as st
# import pandas as pd
# import pickle
# from sklearn.preprocessing import LabelEncoder
# 
# # --- Load the trained model and label encoders ---
# 
# @st.cache_resource
# def load_model(model_path='linear_regression_model.pkl'):
#     with open(model_path, 'rb') as file:
#         model = pickle.load(file)
#     return model
# 
# @st.cache_resource
# def load_label_encoders(encoders_path='label_encoders.pkl'):
#     with open(encoders_path, 'rb') as file:
#         label_encoders = pickle.load(file)
#     return label_encoders
# 
# model = load_model()
# label_encoders = load_label_encoders()
# 
# # Get the list of original column names from one of the encoders (e.g., 'Company Name')
# # This is a heuristic; ideally, we'd save feature names directly.
# # For now, let's assume the order of features is fixed as per X_train in the notebook:
# # 'Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles'
# 
# # Load the dataset (ensure this file is in the same directory as deploy_app.py when deployed)
# df = pd.read_csv('Salary_Dataset_DataScienceLovers (1).csv')
# 
# # --- Streamlit UI ---
# st.set_page_config(page_title='Salary Prediction App', page_icon=':moneybag:')
# 
# st.title('Job Salary Prediction')
# st.write('Enter the details below to predict the salary.')
# 
# # --- Input fields ---
# rating = st.slider('Rating', 1.0, 5.0, 3.5, 0.1)
# company_name_input = st.text_input('Company Name')
# job_title_input = st.text_input('Job Title')
# salaries_reported = st.number_input('Salaries Reported', min_value=1, value=1)
# location_input = st.text_input('Location')
# employment_status_input = st.selectbox('Employment Status', ['Full Time', 'Intern', 'Contract', 'Part Time'])
# job_roles_input = st.text_input('Job Roles') # Assuming Job Roles are provided as text initially
# 
# # --- Prediction logic ---
# if st.button('Predict Salary'):
#     # Preprocess inputs
#     input_data = pd.DataFrame({
#         'Rating': [rating],
#         'Company Name': [company_name_input],
#         'Job Title': [job_title_input],
#         'Salaries Reported': [salaries_reported],
#         'Location': [location_input],
#         'Employment Status': [employment_status_input],
#         'Job Roles': [job_roles_input]
#     })
# 
#     # Apply Label Encoding using the loaded encoders
#     encoded_input = input_data.copy()
#     for col in ['Company Name', 'Job Title', 'Location', 'Employment Status', 'Job Roles']:
#         if col in label_encoders:
#             try:
#                 # Use transform for known labels
#                 encoded_input[col] = label_encoders[col].transform(encoded_input[col])
#             except ValueError:
#                 # Handle unseen labels: assign a default value or treat as unknown
#                 # For simplicity here, we'll assign a common encoded value (e.g., 0)
#                 # In a real app, you might want more sophisticated handling or error messages
#                 st.warning(f"'{input_data[col].iloc[0]}' for {col} is an unseen value. Assigning default value (0).")
#                 encoded_input[col] = 0
#         else:
#             st.error(f"Label encoder for '{col}' not found. Cannot preprocess.")
#             st.stop()
# 
#     # Ensure column order matches training data (important for many models like Linear Regression)
#     # The order of X_train columns was: 'Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles'
#     # Make sure this matches the order of encoded_input columns
#     # This assumes 'Salary' was dropped, so these are the 7 features.
#     feature_cols = ['Rating', 'Company Name', 'Job Title', 'Salaries Reported', 'Location', 'Employment Status', 'Job Roles']
#     encoded_input = encoded_input[feature_cols]
# 
#     # Make prediction
#     prediction = model.predict(encoded_input)
# 
#     st.success(f'Predicted Salary: ₹{prediction[0]:,.2f}')
# 
# st.write('---')
# st.markdown("Developed by Your Name/Team")

import streamlit as st

# Install streamlit if not already installed
!pip install streamlit -q

# Run the Streamlit app in the background.
# This will launch the app in the output frame below this cell.
!streamlit run deploy_app.py --server.port 8501